# permissions for end users to edit memcacheddeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: memcached-operator
    app.kubernetes.io/managed-by: kustomize
  name: memcacheddeployment-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - memcacheddeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - memcacheddeployments/status
  verbs:
  - get
